import Typewriter from "typewriter-effect";
import SideNavbar from "../components/SideNavbar";
import Goals from "../components/goals";
import Head from "next/head";
   
  export default function Home() {
    return (
      <div>
        <Head>
          <title>Responsive FullScreen Navbar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/pro.ico" />
          <link rel="stylesheet" href="style.css" />
          <script type="module" src="C:\Users\dell\Desktop\Hello World\advjs\my-project\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js" > </script>
        </Head>
      <SideNavbar/>
      <Goals/>
       <h1 className=" text-yellow-500  text-6xl mt-32 mx-20 font-bold"> SKILLUP </h1>
       </div>

    );
  }


  